import React, { ReactNode } from 'react';
import logo from '../../../resources/images/logo.png';

interface PrintableReportLayoutProps {
  children: ReactNode;
  title: string;
  subtitle?: string;
  dateRange?: { start: string; end: string };
  showFooter?: boolean;
  showLogo?: boolean;
  className?: string;
}

export function PrintableReportLayout({
  children,
  title,
  subtitle,
  dateRange,
  showFooter = true,
  showLogo = true,
  className = '',
}: PrintableReportLayoutProps) {
  const generatedDate = new Date().toLocaleString('en-PH', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-PH', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const dateRangeText = dateRange?.start && dateRange?.end
    ? `${formatDate(dateRange.start)} – ${formatDate(dateRange.end)}`
    : 'All dates';

  return (
    <div id="printable-report" className={className}>
      <div className="print-header">
        <div className="print-header-top">
          {showLogo && (
            <div className="print-logo-container">
              <img 
                src={logo} 
                alt="Hotel Logo" 
                className="print-logo"
                onError={(e) => {
                  (e.target as HTMLImageElement).style.display = 'none';
                }}
              />
            </div>
          )}
          <div className="print-header-text">
            <h1>{title}</h1>
            <div className="subtitle">
              {subtitle && <span>{subtitle}</span>}
              {dateRangeText && (
                <span>
                  {subtitle && ' · '}
                  {dateRangeText}
                </span>
              )}
            </div>
            <div className="generated-date">Generated: {generatedDate}</div>
          </div>
        </div>
      </div>

      <div className="print-content">{children}</div>

      {showFooter && (
        <div className="print-footer">
          <div className="print-footer-left">
            <span>Generated by Hotel Management System</span>
          </div>
          <div className="print-footer-right">
            <span>Page <span className="page-number" /> of <span className="total-pages" /></span>
          </div>
        </div>
      )}
    </div>
  );
}

interface PrintableStatCardProps {
  label: string;
  value: string | number;
  className?: string;
  valueClassName?: string;
}

export function PrintableStatCard({
  label,
  value,
  className = '',
  valueClassName = '',
}: PrintableStatCardProps) {
  return (
    <div className={`print-stat-card ${className}`}>
      <div className="stat-label">{label}</div>
      <div className={`stat-value ${valueClassName}`}>{value}</div>
    </div>
  );
}

interface PrintableStatsGridProps {
  children: ReactNode;
  columns?: 1 | 2 | 3 | 4 | 5;
  className?: string;
}

export function PrintableStatsGrid({
  children,
  columns = 4,
  className = '',
}: PrintableStatsGridProps) {
  return (
    <div 
      className={`print-stats-grid ${className}`}
      style={{
        gridTemplateColumns: `repeat(${columns}, 1fr)`,
      }}
    >
      {children}
    </div>
  );
}

interface PrintableTableProps {
  children: ReactNode;
  className?: string;
}

export function PrintableTable({ children, className = '' }: PrintableTableProps) {
  return <table className={className}>{children}</table>;
}

interface PrintableCardProps {
  title?: string;
  children: ReactNode;
  className?: string;
  noBreak?: boolean;
}

export function PrintableCard({
  title,
  children,
  className = '',
  noBreak = true,
}: PrintableCardProps) {
  return (
    <div 
      className={`print-card ${className}`}
      style={{ pageBreakInside: noBreak ? 'avoid' : 'auto' }}
    >
      {title && <div className="print-card-title">{title}</div>}
      {children}
    </div>
  );
}

interface PrintableGridProps {
  children: ReactNode;
  columns?: 2 | 3;
  className?: string;
}

export function PrintableGrid({
  children,
  columns = 2,
  className = '',
}: PrintableGridProps) {
  return (
    <div className={`print-grid-${columns} ${className}`}>
      {React.Children.map(children, (child) => (
        <div className="print-grid-item">{child}</div>
      ))}
    </div>
  );
}

interface PrintableBadgeProps {
  children: ReactNode;
  variant?: 'default' | 'success' | 'warning' | 'danger' | 'info';
  className?: string;
}

export function PrintableBadge({
  children,
  variant = 'default',
  className = '',
}: PrintableBadgeProps) {
  const variantClass = `print-badge-${variant}`;
  return (
    <span className={`print-badge ${variantClass} ${className}`}>{children}</span>
  );
}

export function PrintPageBreak() {
  return <div className="print-page-break" />;
}

export function PrintDivider() {
  return <hr className="print-divider" />;
}